/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ssb_droidsound_GMEPlugin */

#ifndef _Included_com_ssb_droidsound_GMEPlugin
#define _Included_com_ssb_droidsound_GMEPlugin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ssb_droidsound_GMEPlugin
 * Method:    N_canHandle
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ssb_droidsound_GMEPlugin_N_1canHandle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ssb_droidsound_GMEPlugin
 * Method:    N_load
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ssb_droidsound_GMEPlugin_N_1load
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_ssb_droidsound_GMEPlugin
 * Method:    N_unload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ssb_droidsound_GMEPlugin_N_1unload
  (JNIEnv *, jobject);

/*
 * Class:     com_ssb_droidsound_GMEPlugin
 * Method:    N_getSoundData
 * Signature: ([SI)I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_GMEPlugin_N_1getSoundData
  (JNIEnv *, jobject, jshortArray, jint);

/*
 * Class:     com_ssb_droidsound_GMEPlugin
 * Method:    N_seekTo
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ssb_droidsound_GMEPlugin_N_1seekTo
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ssb_droidsound_GMEPlugin
 * Method:    N_setSong
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ssb_droidsound_GMEPlugin_N_1setSong
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ssb_droidsound_GMEPlugin
 * Method:    N_getStringInfo
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ssb_droidsound_GMEPlugin_N_1getStringInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ssb_droidsound_GMEPlugin
 * Method:    N_getIntInfo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_GMEPlugin_N_1getIntInfo
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
