/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ssb_droidsound_utils_ID3Tag */

#ifndef _Included_com_ssb_droidsound_utils_ID3Tag
#define _Included_com_ssb_droidsound_utils_ID3Tag
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ssb_droidsound_utils_ID3Tag
 * Method:    openID3Tag
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ssb_droidsound_utils_ID3Tag_openID3Tag
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ssb_droidsound_utils_ID3Tag
 * Method:    closeID3Tag
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ssb_droidsound_utils_ID3Tag_closeID3Tag
  (JNIEnv *, jobject);

/*
 * Class:     com_ssb_droidsound_utils_ID3Tag
 * Method:    getStringInfo
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ssb_droidsound_utils_ID3Tag_getStringInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ssb_droidsound_utils_ID3Tag
 * Method:    getIntInfo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_utils_ID3Tag_getIntInfo
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
