/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ssb_droidsound_utils_NativeZipFile */

#ifndef _Included_com_ssb_droidsound_utils_NativeZipFile
#define _Included_com_ssb_droidsound_utils_NativeZipFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ssb_droidsound_utils_NativeZipFile
 * Method:    openZipFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ssb_droidsound_utils_NativeZipFile_openZipFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ssb_droidsound_utils_NativeZipFile
 * Method:    closeZipFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ssb_droidsound_utils_NativeZipFile_closeZipFile
  (JNIEnv *, jobject);

/*
 * Class:     com_ssb_droidsound_utils_NativeZipFile
 * Method:    getCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_utils_NativeZipFile_getCount
  (JNIEnv *, jobject);

/*
 * Class:     com_ssb_droidsound_utils_NativeZipFile
 * Method:    getEntry
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ssb_droidsound_utils_NativeZipFile_getEntry
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ssb_droidsound_utils_NativeZipFile
 * Method:    getSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_utils_NativeZipFile_getSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ssb_droidsound_utils_NativeZipFile
 * Method:    findEntry
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_utils_NativeZipFile_findEntry
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ssb_droidsound_utils_NativeZipFile
 * Method:    readData
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_utils_NativeZipFile_readData
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_ssb_droidsound_utils_NativeZipFile
 * Method:    open
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_ssb_droidsound_utils_NativeZipFile_open
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ssb_droidsound_utils_NativeZipFile
 * Method:    read
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_utils_NativeZipFile_read
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_ssb_droidsound_utils_NativeZipFile
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ssb_droidsound_utils_NativeZipFile_close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
