/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ssb_droidsound_NativeZipFile */

#ifndef _Included_com_ssb_droidsound_NativeZipFile
#define _Included_com_ssb_droidsound_NativeZipFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ssb_droidsound_NativeZipFile
 * Method:    NativeZipFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ssb_droidsound_NativeZipFile_NativeZipFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ssb_droidsound_NativeZipFile
 * Method:    getCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_NativeZipFile_getCount
  (JNIEnv *, jobject);

/*
 * Class:     com_ssb_droidsound_NativeZipFile
 * Method:    getEntry
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ssb_droidsound_NativeZipFile_getEntry
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ssb_droidsound_NativeZipFile
 * Method:    getSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_NativeZipFile_getSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ssb_droidsound_NativeZipFile
 * Method:    findEntry
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_NativeZipFile_findEntry
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ssb_droidsound_NativeZipFile
 * Method:    readData
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_NativeZipFile_readData
  (JNIEnv *, jobject, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
