#ifndef _UADE_CONSTANTS_H_
#define _UADE_CONSTANTS_H_

/* You must not change anything */
#define UADE_CHANNELS (2)
#define UADE_FREQUENCY (44100)
#define UADE_BYTES_PER_SAMPLE (2)
#define UADE_BYTES_PER_SECOND (UADE_CHANNELS * UADE_FREQUENCY * UADE_BYTES_PER_SAMPLE)

#endif
