/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ssb_droidsound_plugins_SC68Plugin */

#ifndef _Included_com_ssb_droidsound_plugins_SC68Plugin
#define _Included_com_ssb_droidsound_plugins_SC68Plugin
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ssb_droidsound_plugins_SC68Plugin_INFO_TITLE
#define com_ssb_droidsound_plugins_SC68Plugin_INFO_TITLE 0L
#undef com_ssb_droidsound_plugins_SC68Plugin_INFO_AUTHOR
#define com_ssb_droidsound_plugins_SC68Plugin_INFO_AUTHOR 1L
#undef com_ssb_droidsound_plugins_SC68Plugin_INFO_LENGTH
#define com_ssb_droidsound_plugins_SC68Plugin_INFO_LENGTH 2L
#undef com_ssb_droidsound_plugins_SC68Plugin_INFO_TYPE
#define com_ssb_droidsound_plugins_SC68Plugin_INFO_TYPE 3L
#undef com_ssb_droidsound_plugins_SC68Plugin_INFO_COPYRIGHT
#define com_ssb_droidsound_plugins_SC68Plugin_INFO_COPYRIGHT 4L
#undef com_ssb_droidsound_plugins_SC68Plugin_INFO_GAME
#define com_ssb_droidsound_plugins_SC68Plugin_INFO_GAME 5L
#undef com_ssb_droidsound_plugins_SC68Plugin_INFO_SUBTUNE_COUNT
#define com_ssb_droidsound_plugins_SC68Plugin_INFO_SUBTUNE_COUNT 6L
#undef com_ssb_droidsound_plugins_SC68Plugin_INFO_STARTTUNE
#define com_ssb_droidsound_plugins_SC68Plugin_INFO_STARTTUNE 7L
#undef com_ssb_droidsound_plugins_SC68Plugin_INFO_SUBTUNE_TITLE
#define com_ssb_droidsound_plugins_SC68Plugin_INFO_SUBTUNE_TITLE 8L
#undef com_ssb_droidsound_plugins_SC68Plugin_INFO_SUBTUNE_AUTHOR
#define com_ssb_droidsound_plugins_SC68Plugin_INFO_SUBTUNE_AUTHOR 9L
#undef com_ssb_droidsound_plugins_SC68Plugin_INFO_SUBTUNE_NO
#define com_ssb_droidsound_plugins_SC68Plugin_INFO_SUBTUNE_NO 10L
#undef com_ssb_droidsound_plugins_SC68Plugin_SIZEOF_INFO
#define com_ssb_droidsound_plugins_SC68Plugin_SIZEOF_INFO 11L
#undef com_ssb_droidsound_plugins_SC68Plugin_OPT_FILTER
#define com_ssb_droidsound_plugins_SC68Plugin_OPT_FILTER 1L
#undef com_ssb_droidsound_plugins_SC68Plugin_OPT_RESAMPLING
#define com_ssb_droidsound_plugins_SC68Plugin_OPT_RESAMPLING 2L
#undef com_ssb_droidsound_plugins_SC68Plugin_OPT_NTSC
#define com_ssb_droidsound_plugins_SC68Plugin_OPT_NTSC 3L
#undef com_ssb_droidsound_plugins_SC68Plugin_OPT_SPEED_HACK
#define com_ssb_droidsound_plugins_SC68Plugin_OPT_SPEED_HACK 4L
#undef com_ssb_droidsound_plugins_SC68Plugin_OPT_PANNING
#define com_ssb_droidsound_plugins_SC68Plugin_OPT_PANNING 5L
/*
 * Class:     com_ssb_droidsound_plugins_SC68Plugin
 * Method:    N_load
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_com_ssb_droidsound_plugins_SC68Plugin_N_1load
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_ssb_droidsound_plugins_SC68Plugin
 * Method:    N_loadInfo
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_com_ssb_droidsound_plugins_SC68Plugin_N_1loadInfo
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_ssb_droidsound_plugins_SC68Plugin
 * Method:    N_unload
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ssb_droidsound_plugins_SC68Plugin_N_1unload
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ssb_droidsound_plugins_SC68Plugin
 * Method:    N_getSoundData
 * Signature: (J[SI)I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_plugins_SC68Plugin_N_1getSoundData
  (JNIEnv *, jobject, jlong, jshortArray, jint);

/*
 * Class:     com_ssb_droidsound_plugins_SC68Plugin
 * Method:    N_seekTo
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ssb_droidsound_plugins_SC68Plugin_N_1seekTo
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ssb_droidsound_plugins_SC68Plugin
 * Method:    N_setTune
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ssb_droidsound_plugins_SC68Plugin_N_1setTune
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ssb_droidsound_plugins_SC68Plugin
 * Method:    N_getStringInfo
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ssb_droidsound_plugins_SC68Plugin_N_1getStringInfo
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ssb_droidsound_plugins_SC68Plugin
 * Method:    N_getIntInfo
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_plugins_SC68Plugin_N_1getIntInfo
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_ssb_droidsound_plugins_SC68Plugin
 * Method:    N_setDataDir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ssb_droidsound_plugins_SC68Plugin_N_1setDataDir
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ssb_droidsound_plugins_SC68Plugin
 * Method:    N_unice
 * Signature: ([B[B)V
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_plugins_SC68Plugin_N_1unice
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
