/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ssb_droidsound_utils_FFT */

#ifndef _Included_com_ssb_droidsound_utils_FFT
#define _Included_com_ssb_droidsound_utils_FFT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ssb_droidsound_utils_FFT
 * Method:    fft
 * Signature: ([S[S)V
 */
JNIEXPORT void JNICALL Java_com_ssb_droidsound_utils_FFT_fft
  (JNIEnv *, jclass, jshortArray, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
