/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ssb_droidsound_plugins_VICEPlugin */

#ifndef _Included_com_ssb_droidsound_plugins_VICEPlugin
#define _Included_com_ssb_droidsound_plugins_VICEPlugin
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ssb_droidsound_plugins_VICEPlugin_INFO_TITLE
#define com_ssb_droidsound_plugins_VICEPlugin_INFO_TITLE 0L
#undef com_ssb_droidsound_plugins_VICEPlugin_INFO_AUTHOR
#define com_ssb_droidsound_plugins_VICEPlugin_INFO_AUTHOR 1L
#undef com_ssb_droidsound_plugins_VICEPlugin_INFO_LENGTH
#define com_ssb_droidsound_plugins_VICEPlugin_INFO_LENGTH 2L
#undef com_ssb_droidsound_plugins_VICEPlugin_INFO_TYPE
#define com_ssb_droidsound_plugins_VICEPlugin_INFO_TYPE 3L
#undef com_ssb_droidsound_plugins_VICEPlugin_INFO_COPYRIGHT
#define com_ssb_droidsound_plugins_VICEPlugin_INFO_COPYRIGHT 4L
#undef com_ssb_droidsound_plugins_VICEPlugin_INFO_GAME
#define com_ssb_droidsound_plugins_VICEPlugin_INFO_GAME 5L
#undef com_ssb_droidsound_plugins_VICEPlugin_INFO_SUBTUNE_COUNT
#define com_ssb_droidsound_plugins_VICEPlugin_INFO_SUBTUNE_COUNT 6L
#undef com_ssb_droidsound_plugins_VICEPlugin_INFO_STARTTUNE
#define com_ssb_droidsound_plugins_VICEPlugin_INFO_STARTTUNE 7L
#undef com_ssb_droidsound_plugins_VICEPlugin_INFO_SUBTUNE_TITLE
#define com_ssb_droidsound_plugins_VICEPlugin_INFO_SUBTUNE_TITLE 8L
#undef com_ssb_droidsound_plugins_VICEPlugin_INFO_SUBTUNE_AUTHOR
#define com_ssb_droidsound_plugins_VICEPlugin_INFO_SUBTUNE_AUTHOR 9L
#undef com_ssb_droidsound_plugins_VICEPlugin_INFO_SUBTUNE_NO
#define com_ssb_droidsound_plugins_VICEPlugin_INFO_SUBTUNE_NO 10L
#undef com_ssb_droidsound_plugins_VICEPlugin_SIZEOF_INFO
#define com_ssb_droidsound_plugins_VICEPlugin_SIZEOF_INFO 11L
#undef com_ssb_droidsound_plugins_VICEPlugin_OPT_FILTER
#define com_ssb_droidsound_plugins_VICEPlugin_OPT_FILTER 1L
#undef com_ssb_droidsound_plugins_VICEPlugin_OPT_RESAMPLING
#define com_ssb_droidsound_plugins_VICEPlugin_OPT_RESAMPLING 2L
#undef com_ssb_droidsound_plugins_VICEPlugin_OPT_NTSC
#define com_ssb_droidsound_plugins_VICEPlugin_OPT_NTSC 3L
#undef com_ssb_droidsound_plugins_VICEPlugin_OPT_SPEED_HACK
#define com_ssb_droidsound_plugins_VICEPlugin_OPT_SPEED_HACK 4L
#undef com_ssb_droidsound_plugins_VICEPlugin_OPT_PANNING
#define com_ssb_droidsound_plugins_VICEPlugin_OPT_PANNING 5L
#undef com_ssb_droidsound_plugins_VICEPlugin_OPT_FILTER_BIAS
#define com_ssb_droidsound_plugins_VICEPlugin_OPT_FILTER_BIAS 6L
#undef com_ssb_droidsound_plugins_VICEPlugin_OPT_SID_MODEL
#define com_ssb_droidsound_plugins_VICEPlugin_OPT_SID_MODEL 7L
/*
 * Class:     com_ssb_droidsound_plugins_VICEPlugin
 * Method:    N_loadFile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ssb_droidsound_plugins_VICEPlugin_N_1loadFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ssb_droidsound_plugins_VICEPlugin
 * Method:    N_unload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ssb_droidsound_plugins_VICEPlugin_N_1unload
  (JNIEnv *, jclass);

/*
 * Class:     com_ssb_droidsound_plugins_VICEPlugin
 * Method:    N_getSoundData
 * Signature: ([SI)I
 */
JNIEXPORT jint JNICALL Java_com_ssb_droidsound_plugins_VICEPlugin_N_1getSoundData
  (JNIEnv *, jclass, jshortArray, jint);

/*
 * Class:     com_ssb_droidsound_plugins_VICEPlugin
 * Method:    N_setTune
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ssb_droidsound_plugins_VICEPlugin_N_1setTune
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ssb_droidsound_plugins_VICEPlugin
 * Method:    N_setOption
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_ssb_droidsound_plugins_VICEPlugin_N_1setOption
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_ssb_droidsound_plugins_VICEPlugin
 * Method:    N_setDataDir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ssb_droidsound_plugins_VICEPlugin_N_1setDataDir
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
